# Generated by Django 5.0.6 on 2024-07-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='image',
            new_name='photo',
        ),
    ]
